logging:

  level:

    ROOT: ${log-framework:WARN}

    ru.tchallenge: ${log:INFO}

server:

  error.whitelabel.enabled: 'false'

  port: ${port:5000}

spring:

  main.banner-mode: 'off'

  mvc.throw-exception-if-no-handler-found: 'true'

  resources.add-mappings: 'false'

tchallenge:

  asset.vendor.prefix: ${vendor-asset-prefix:https://cdnjs.cloudflare.com/ajax/libs/}

  template.cache.enabled: false
